version: "2.3"
services:
    proto-merge:
        image: buildfailure/proto-merge:latest
        build:
            context: .
        volumes:
            - ./test/schema:/schema
        command: ["/schema/organization.proto"]
