version: "2.3"
services:
    proto-merge:
        image: buildfailure/proto-merge:dev
        build:
            context: .
        volumes:
            - ./test/schema:/schema
        stdin_open: true
        tty: true
        entrypoint: ["/bin/bash"]
